using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Samples;

// SAMPLE 7 — GOLDEN EMISSION for the planned "NoahStolk.Unions" library (pure type-union).
//
// This is the exact shape the generator should PRODUCE. The user's INPUT surface would be
// only the case types plus a marker-annotated empty partial struct:
//
//     public readonly record struct Angle(float Value);
//     public readonly record struct Position(Vector3 Value);
//     public readonly record struct Rotation(Quaternion Value);
//
//     [Union]                    // NoahStolk.Unions.UnionAttribute
//     [UnionCase<Angle>]
//     [UnionCase<Position>]
//     [UnionCase<Rotation>]
//     public partial struct Transform;
//
// Everything below `#region generated` is what the generator emits. It proves the four
// properties that matter: (1) native exhaustive match, no default arm; (2) zero alloc on
// construct + match; (3) ref access to a payload; (4) value equality — all without the
// Switch/Match delegates, US0001 analyzer, or CS8509 suppressor the old library needed.
public static class S07_GoldenEmission
{
    public static void Run()
    {
        Console.WriteLine("[S07] Golden emission (pure type-union, generator target)");

        // Construction via constructor or implicit conversion.
        Transform a = new Angle(1.5f);
        Transform p = new Position(new Vector3(3, 4, 0));

        // (1) Native exhaustive switch — NO default arm.
        Console.WriteLine($"  match: {Describe(a)} | {Describe(p)}");

        // (3) ref access straight into the union's overlapped storage — zero copy.
        //     (case types are readonly records, so we write the payload through the ref)
        ref Position slot = ref p.PositionData;
        slot = new Position(new Vector3(13, 4, 0));
        Console.WriteLine($"  after ref mutate: {Describe(p)}");

        // (4) value equality.
        Transform p2 = new Position(new Vector3(13, 4, 0));
        Console.WriteLine($"  equality after mutate: p == p2 -> {p == p2}");

        // (2) zero-allocation construct + match.
        for (int i = 0; i < 1000; i++) _ = Score(new Angle(i));   // warm up
        long before = GC.GetAllocatedBytesForCurrentThread();
        double acc = 0;
        for (int i = 0; i < 1_000_000; i++)
        {
            Transform t = (i & 1) == 0 ? new Angle(i) : new Position(new Vector3(i, 0, 0));
            acc += Score(t);
        }
        long bytes = GC.GetAllocatedBytesForCurrentThread() - before;
        Console.WriteLine($"  sizeof(Transform) = {Unsafe.SizeOf<Transform>()} bytes; 1M construct+match = {bytes:N0} bytes (acc={acc:F0})\n");
    }

    static string Describe(Transform t) => t switch
    {
        Angle x => $"Angle({x.Value})",
        Position x => $"Position({x.Value.X},{x.Value.Y},{x.Value.Z})",
        Rotation x => $"Rotation({x.Value})",
    };

    static double Score(Transform t) => t switch
    {
        Angle x => x.Value,
        Position x => x.Value.X,
        Rotation x => x.Value.W,
    };
}

// ---- user-declared case types ----
public readonly record struct Angle(float Value);
public readonly record struct Position(Vector3 Value);
public readonly record struct Rotation(Quaternion Value);

#region generated by NoahStolk.Unions (target)
[Union]
[StructLayout(LayoutKind.Explicit)]   // all case types unmanaged & non-generic => overlap
public partial struct Transform : IUnion, IEquatable<Transform>
{
    public const int AngleIndex = 0;
    public const int PositionIndex = 1;
    public const int RotationIndex = 2;

    [FieldOffset(0)] public readonly int CaseIndex;   // fast-path/int-switch + fallback
    [FieldOffset(4)] public Angle AngleData;          // public => callers can `ref` it
    [FieldOffset(4)] public Position PositionData;
    [FieldOffset(4)] public Rotation RotationData;

    // Constructors define the case set for the compiler.
    public Transform(Angle value) { this = default; CaseIndex = AngleIndex; AngleData = value; }
    public Transform(Position value) { this = default; CaseIndex = PositionIndex; PositionData = value; }
    public Transform(Rotation value) { this = default; CaseIndex = RotationIndex; RotationData = value; }

    // Convenience implicit conversions.
    public static implicit operator Transform(Angle value) => new(value);
    public static implicit operator Transform(Position value) => new(value);
    public static implicit operator Transform(Rotation value) => new(value);

    // IUnion contract — lazy-boxes only if explicitly read. Declared NON-nullable
    // `object` (not `object?`): a maybe-null Value re-introduces the CS8655 null-arm
    // warning on otherwise-exhaustive switches, so the generator must emit it this way.
    public object Value => CaseIndex switch { AngleIndex => AngleData, PositionIndex => PositionData, _ => RotationData };

    // Non-boxing access pattern — the compiler prefers these for pattern matching.
    public bool HasValue => true;   // pins Value's null-state to "not null" => no CS8655
    public bool TryGetValue(out Angle value) { value = AngleData; return CaseIndex == AngleIndex; }
    public bool TryGetValue(out Position value) { value = PositionData; return CaseIndex == PositionIndex; }
    public bool TryGetValue(out Rotation value) { value = RotationData; return CaseIndex == RotationIndex; }

    // Equality (the language does not synthesize this for unions).
    public bool Equals(Transform other) => CaseIndex == other.CaseIndex && CaseIndex switch
    {
        AngleIndex => AngleData.Equals(other.AngleData),
        PositionIndex => PositionData.Equals(other.PositionData),
        RotationIndex => RotationData.Equals(other.RotationData),
        _ => true,
    };
    public override bool Equals(object? obj) => obj is Transform o && Equals(o);
    public override int GetHashCode() => CaseIndex switch
    {
        AngleIndex => HashCode.Combine(CaseIndex, AngleData),
        PositionIndex => HashCode.Combine(CaseIndex, PositionData),
        RotationIndex => HashCode.Combine(CaseIndex, RotationData),
        _ => CaseIndex,
    };
    public static bool operator ==(Transform left, Transform right) => left.Equals(right);
    public static bool operator !=(Transform left, Transform right) => !left.Equals(right);

    public override string ToString() => CaseIndex switch
    {
        AngleIndex => $"Angle {{ Value = {AngleData.Value} }}",
        PositionIndex => $"Position {{ Value = {PositionData.Value} }}",
        RotationIndex => $"Rotation {{ Value = {RotationData.Value} }}",
        _ => "<invalid>",
    };
}
#endregion
