//HintName: UnionStructAttributes.g.cs
// <auto-generated>
// This code was generated by UnionStruct.
// </auto-generated>

#nullable enable

namespace UnionStruct;

[global::System.AttributeUsage(global::System.AttributeTargets.Struct)]
internal sealed class UnionAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
internal sealed class UnionCaseAttribute : global::System.Attribute
{
	public string? DisplayName { get; set; }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false)]
internal sealed class GeneratedUnionAttribute : global::System.Attribute
{
}