//HintName: UnionAttribute.g.cs
// <auto-generated>
// This code was generated by UnionStruct.
// </auto-generated>

#nullable enable

namespace UnionStruct;

[global::System.AttributeUsage(global::System.AttributeTargets.Struct)]
public sealed class UnionAttribute : global::System.Attribute;