//HintName: TestUnion.g.cs
// <auto-generated>
// This code was generated by UnionStruct.
// </auto-generated>

#nullable enable

namespace Tests;

[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
internal partial struct TestUnion : global::System.IEquatable<TestUnion>
{
	public const global::System.Int32 EmptyIndex = 0;
	public const global::System.Int32 PositionCaseIndex = 1;
	public const global::System.Int32 MultiCaseIndex = 2;

	[global::System.Runtime.InteropServices.FieldOffset(0)]
	public readonly global::System.Int32 CaseIndex;

	[global::System.Runtime.InteropServices.FieldOffset(4)]
	public System.Numerics.Vector3 PositionCaseData;

	[global::System.Runtime.InteropServices.FieldOffset(4)]
	public MultiCaseCase MultiCaseData;

	private TestUnion(global::System.Int32 caseIndex)
	{
		CaseIndex = caseIndex;
	}

	public readonly bool IsEmpty => CaseIndex == EmptyIndex;
	public readonly bool IsPositionCase => CaseIndex == PositionCaseIndex;
	public readonly bool IsMultiCase => CaseIndex == MultiCaseIndex;

	public static global::System.ReadOnlySpan<global::System.Byte> NullTerminatedMemberNames => "Empty\0PositionCase\0MultiCase\0"u8;

	public static partial TestUnion Empty(
	)
	{
		TestUnion ___factoryReturnValue = new(EmptyIndex);
		return ___factoryReturnValue;
	}

	public static partial TestUnion PositionCase(
		System.Numerics.Vector3 @position
	)
	{
		TestUnion ___factoryReturnValue = new(PositionCaseIndex);
		___factoryReturnValue.PositionCaseData = @position;
		return ___factoryReturnValue;
	}

	public static partial TestUnion MultiCase(
		System.Numerics.Vector3 @position,
		System.Numerics.Vector3 @velocity
	)
	{
		TestUnion ___factoryReturnValue = new(MultiCaseIndex);
		___factoryReturnValue.MultiCaseData = new(@position, @velocity);
		return ___factoryReturnValue;
	}

	public void Switch(
		global::System.Action @empty,
		global::System.Action<System.Numerics.Vector3> @positionCase,
		global::System.Action<System.Numerics.Vector3, System.Numerics.Vector3> @multiCase
	)
	{
		switch (CaseIndex)
		{
			case EmptyIndex: @empty.Invoke(); break;
			case PositionCaseIndex: @positionCase.Invoke(PositionCaseData); break;
			case MultiCaseIndex: @multiCase.Invoke(MultiCaseData.Position, MultiCaseData.Velocity); break;
			default: throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}.");
		}
	}

	public TMatchOut Match<TMatchOut>(
		global::System.Func<TMatchOut> @empty,
		global::System.Func<System.Numerics.Vector3, TMatchOut> @positionCase,
		global::System.Func<System.Numerics.Vector3, System.Numerics.Vector3, TMatchOut> @multiCase
	)
	{
		return CaseIndex switch
		{
			EmptyIndex => @empty.Invoke(),
			PositionCaseIndex => @positionCase.Invoke(PositionCaseData),
			MultiCaseIndex => @multiCase.Invoke(MultiCaseData.Position, MultiCaseData.Velocity),
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}."),
		};
	}

	public override global::System.String ToString()
	{
		return CaseIndex switch
		{
			EmptyIndex => "Empty",
			PositionCaseIndex => $"PositionCase {{ Position = {PositionCaseData} }}",
			MultiCaseIndex => $"MultiCase {{ Position = {MultiCaseData.Position}, Velocity = {MultiCaseData.Velocity} }}",
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}."),
		};
	}

	public static global::System.String GetTypeString(global::System.Int32 caseIndex)
	{
		return caseIndex switch
		{
			EmptyIndex => "Empty",
			PositionCaseIndex => "PositionCase",
			MultiCaseIndex => "MultiCase",
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {caseIndex}."),
		};
	}

	public global::System.String GetTypeString()
	{
		return GetTypeString(CaseIndex);
	}

	public static global::System.ReadOnlySpan<global::System.Byte> GetTypeAsUtf8Span(global::System.Int32 caseIndex)
	{
		return caseIndex switch
		{
			EmptyIndex => "Empty"u8,
			PositionCaseIndex => "PositionCase"u8,
			MultiCaseIndex => "MultiCase"u8,
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {caseIndex}."),
		};
	}

	public global::System.ReadOnlySpan<global::System.Byte> GetTypeAsUtf8Span()
	{
		return GetTypeAsUtf8Span(CaseIndex);
	}

	public static bool operator !=(TestUnion left, TestUnion right)
	{
		return !(left == right);
	}

	public static bool operator ==(TestUnion left, TestUnion right)
	{
		return left.Equals(right);
	}

	public override global::System.Int32 GetHashCode()
	{
		return CaseIndex switch
		{
			EmptyIndex => unchecked ( EmptyIndex ),
			PositionCaseIndex => unchecked ( PositionCaseIndex * -1521134295 + global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.GetHashCode(PositionCaseData) ),
			MultiCaseIndex => unchecked ( MultiCaseIndex * -1521134295 + global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.GetHashCode(MultiCaseData.Position) * -1521134295 + global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.GetHashCode(MultiCaseData.Velocity) ),
			_ => 3,
		};
	}

	public override global::System.Boolean Equals(global::System.Object? obj)
	{
		return obj is TestUnion && Equals((TestUnion)obj);
	}

	public global::System.Boolean Equals(TestUnion other)
	{
		return CaseIndex == other.CaseIndex && CaseIndex switch
		{
			EmptyIndex => true,
			PositionCaseIndex => global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.Equals(PositionCaseData, other.PositionCaseData),
			MultiCaseIndex => global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.Equals(MultiCaseData.Position, other.MultiCaseData.Position) && global::System.Collections.Generic.EqualityComparer<System.Numerics.Vector3>.Default.Equals(MultiCaseData.Velocity, other.MultiCaseData.Velocity),
			_ => true,
		};
	}

	public struct MultiCaseCase
	{
		public System.Numerics.Vector3 Position;

		public System.Numerics.Vector3 Velocity;

		public MultiCaseCase(
			System.Numerics.Vector3 @position,
			System.Numerics.Vector3 @velocity
		)
		{
			Position = @position;
			Velocity = @velocity;
		}
	}

}
