//HintName: ComplexUnion(T1, T2).g.cs
// <auto-generated>
// This code was generated by UnionStruct.
// </auto-generated>

#nullable enable

namespace Tests;

internal partial struct ComplexUnion<T1, T2> : global::System.IEquatable<ComplexUnion<T1, T2>>
{
	public const global::System.Int32 IntIndex = 0;
	public const global::System.Int32 LongIndex = 1;
	public const global::System.Int32 TCaseIndex = 2;
	public const global::System.Int32 UCaseIndex = 3;
	public const global::System.Int32 UCaseNestedIndex = 4;

	public readonly global::System.Int32 CaseIndex;

	public int? IntData;

	public long? LongData;

	public T1? TCaseData;

	public UCaseCase UCaseData;

	public UCaseNestedCase UCaseNestedData;

	private ComplexUnion(global::System.Int32 caseIndex)
	{
		CaseIndex = caseIndex;
	}

	public readonly bool IsInt => CaseIndex == IntIndex;
	public readonly bool IsLong => CaseIndex == LongIndex;
	public readonly bool IsTCase => CaseIndex == TCaseIndex;
	public readonly bool IsUCase => CaseIndex == UCaseIndex;
	public readonly bool IsUCaseNested => CaseIndex == UCaseNestedIndex;

	public static global::System.ReadOnlySpan<global::System.Byte> NullTerminatedMemberNames => "Int\0Long\0TCase\0UCase\0UCaseNested\0"u8;

	public static partial ComplexUnion<T1, T2> Int(
		int? @value
	)
	{
		ComplexUnion<T1, T2> ___factoryReturnValue = new(IntIndex);
		___factoryReturnValue.IntData = @value;
		return ___factoryReturnValue;
	}

	public static partial ComplexUnion<T1, T2> Long(
		long? @value
	)
	{
		ComplexUnion<T1, T2> ___factoryReturnValue = new(LongIndex);
		___factoryReturnValue.LongData = @value;
		return ___factoryReturnValue;
	}

	public static partial ComplexUnion<T1, T2> TCase(
		T1? @value
	)
	{
		ComplexUnion<T1, T2> ___factoryReturnValue = new(TCaseIndex);
		___factoryReturnValue.TCaseData = @value;
		return ___factoryReturnValue;
	}

	public static partial ComplexUnion<T1, T2> UCase(
		Tests.TestGeneric<byte, short>? @value,
		T1 @a,
		T2 @b
	)
	{
		ComplexUnion<T1, T2> ___factoryReturnValue = new(UCaseIndex);
		___factoryReturnValue.UCaseData = new(@value, @a, @b);
		return ___factoryReturnValue;
	}

	public static partial ComplexUnion<T1, T2> UCaseNested(
		Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>? @value,
		T1 @a,
		T2 @b
	)
	{
		ComplexUnion<T1, T2> ___factoryReturnValue = new(UCaseNestedIndex);
		___factoryReturnValue.UCaseNestedData = new(@value, @a, @b);
		return ___factoryReturnValue;
	}

	public void Switch(
		global::System.Action<int?> @int,
		global::System.Action<long?> @long,
		global::System.Action<T1?> @tCase,
		global::System.Action<Tests.TestGeneric<byte, short>?, T1, T2> @uCase,
		global::System.Action<Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>?, T1, T2> @uCaseNested
	)
	{
		switch (CaseIndex)
		{
			case IntIndex: @int.Invoke(IntData); break;
			case LongIndex: @long.Invoke(LongData); break;
			case TCaseIndex: @tCase.Invoke(TCaseData); break;
			case UCaseIndex: @uCase.Invoke(UCaseData.Value, UCaseData.A, UCaseData.B); break;
			case UCaseNestedIndex: @uCaseNested.Invoke(UCaseNestedData.Value, UCaseNestedData.A, UCaseNestedData.B); break;
			default: throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}.");
		}
	}

	public TMatchOut Match<TMatchOut>(
		global::System.Func<int?, TMatchOut> @int,
		global::System.Func<long?, TMatchOut> @long,
		global::System.Func<T1?, TMatchOut> @tCase,
		global::System.Func<Tests.TestGeneric<byte, short>?, T1, T2, TMatchOut> @uCase,
		global::System.Func<Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>?, T1, T2, TMatchOut> @uCaseNested
	)
	{
		return CaseIndex switch
		{
			IntIndex => @int.Invoke(IntData),
			LongIndex => @long.Invoke(LongData),
			TCaseIndex => @tCase.Invoke(TCaseData),
			UCaseIndex => @uCase.Invoke(UCaseData.Value, UCaseData.A, UCaseData.B),
			UCaseNestedIndex => @uCaseNested.Invoke(UCaseNestedData.Value, UCaseNestedData.A, UCaseNestedData.B),
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}."),
		};
	}

	public override global::System.String ToString()
	{
		return CaseIndex switch
		{
			IntIndex => $"Int {{ Value = {IntData} }}",
			LongIndex => $"Long {{ Value = {LongData} }}",
			TCaseIndex => $"TCase {{ Value = {TCaseData} }}",
			UCaseIndex => $"UCase {{ Value = {UCaseData.Value}, A = {UCaseData.A}, B = {UCaseData.B} }}",
			UCaseNestedIndex => $"UCaseNested {{ Value = {UCaseNestedData.Value}, A = {UCaseNestedData.A}, B = {UCaseNestedData.B} }}",
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {CaseIndex}."),
		};
	}

	public static global::System.String GetTypeString(global::System.Int32 caseIndex)
	{
		return caseIndex switch
		{
			IntIndex => "Int",
			LongIndex => "Long",
			TCaseIndex => "TCase",
			UCaseIndex => "UCase",
			UCaseNestedIndex => "UCaseNested",
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {caseIndex}."),
		};
	}

	public global::System.String GetTypeString()
	{
		return GetTypeString(CaseIndex);
	}

	public static global::System.ReadOnlySpan<global::System.Byte> GetTypeAsUtf8Span(global::System.Int32 caseIndex)
	{
		return caseIndex switch
		{
			IntIndex => "Int"u8,
			LongIndex => "Long"u8,
			TCaseIndex => "TCase"u8,
			UCaseIndex => "UCase"u8,
			UCaseNestedIndex => "UCaseNested"u8,
			_ => throw new global::System.Diagnostics.UnreachableException($"Invalid case index: {caseIndex}."),
		};
	}

	public global::System.ReadOnlySpan<global::System.Byte> GetTypeAsUtf8Span()
	{
		return GetTypeAsUtf8Span(CaseIndex);
	}

	public static bool operator !=(ComplexUnion<T1, T2> left, ComplexUnion<T1, T2> right)
	{
		return !(left == right);
	}

	public static bool operator ==(ComplexUnion<T1, T2> left, ComplexUnion<T1, T2> right)
	{
		return left.Equals(right);
	}

	public override global::System.Int32 GetHashCode()
	{
		return CaseIndex switch
		{
			IntIndex => unchecked ( IntIndex * -1521134295 + (IntData.HasValue ? global::System.Collections.Generic.EqualityComparer<int?>.Default.GetHashCode(IntData.Value) : 0) ),
			LongIndex => unchecked ( LongIndex * -1521134295 + (LongData.HasValue ? global::System.Collections.Generic.EqualityComparer<long?>.Default.GetHashCode(LongData.Value) : 0) ),
			TCaseIndex => unchecked ( TCaseIndex * -1521134295 + (TCaseData == null ? 0 : global::System.Collections.Generic.EqualityComparer<T1?>.Default.GetHashCode(TCaseData)) ),
			UCaseIndex => unchecked ( UCaseIndex * -1521134295 + (UCaseData.Value.HasValue ? global::System.Collections.Generic.EqualityComparer<Tests.TestGeneric<byte, short>?>.Default.GetHashCode(UCaseData.Value.Value) : 0) * -1521134295 + (UCaseData.A == null ? 0 : global::System.Collections.Generic.EqualityComparer<T1>.Default.GetHashCode(UCaseData.A)) * -1521134295 + (UCaseData.B == null ? 0 : global::System.Collections.Generic.EqualityComparer<T2>.Default.GetHashCode(UCaseData.B)) ),
			UCaseNestedIndex => unchecked ( UCaseNestedIndex * -1521134295 + (UCaseNestedData.Value.HasValue ? global::System.Collections.Generic.EqualityComparer<Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>?>.Default.GetHashCode(UCaseNestedData.Value.Value) : 0) * -1521134295 + (UCaseNestedData.A == null ? 0 : global::System.Collections.Generic.EqualityComparer<T1>.Default.GetHashCode(UCaseNestedData.A)) * -1521134295 + (UCaseNestedData.B == null ? 0 : global::System.Collections.Generic.EqualityComparer<T2>.Default.GetHashCode(UCaseNestedData.B)) ),
			_ => 5,
		};
	}

	public override global::System.Boolean Equals(global::System.Object? obj)
	{
		return obj is ComplexUnion<T1, T2> && Equals((ComplexUnion<T1, T2>)obj);
	}

	public global::System.Boolean Equals(ComplexUnion<T1, T2> other)
	{
		return CaseIndex == other.CaseIndex && CaseIndex switch
		{
			IntIndex => global::System.Collections.Generic.EqualityComparer<int?>.Default.Equals(IntData, other.IntData),
			LongIndex => global::System.Collections.Generic.EqualityComparer<long?>.Default.Equals(LongData, other.LongData),
			TCaseIndex => global::System.Collections.Generic.EqualityComparer<T1?>.Default.Equals(TCaseData, other.TCaseData),
			UCaseIndex => global::System.Collections.Generic.EqualityComparer<Tests.TestGeneric<byte, short>?>.Default.Equals(UCaseData.Value, other.UCaseData.Value) && global::System.Collections.Generic.EqualityComparer<T1>.Default.Equals(UCaseData.A, other.UCaseData.A) && global::System.Collections.Generic.EqualityComparer<T2>.Default.Equals(UCaseData.B, other.UCaseData.B),
			UCaseNestedIndex => global::System.Collections.Generic.EqualityComparer<Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>?>.Default.Equals(UCaseNestedData.Value, other.UCaseNestedData.Value) && global::System.Collections.Generic.EqualityComparer<T1>.Default.Equals(UCaseNestedData.A, other.UCaseNestedData.A) && global::System.Collections.Generic.EqualityComparer<T2>.Default.Equals(UCaseNestedData.B, other.UCaseNestedData.B),
			_ => true,
		};
	}

	public struct UCaseCase
	{
		public Tests.TestGeneric<byte, short>? Value;

		public T1 A;

		public T2 B;

		public UCaseCase(
			Tests.TestGeneric<byte, short>? @value,
			T1 @a,
			T2 @b
		)
		{
			Value = @value;
			A = @a;
			B = @b;
		}
	}

	public struct UCaseNestedCase
	{
		public Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>? Value;

		public T1 A;

		public T2 B;

		public UCaseNestedCase(
			Tests.ComplexUnion<T1, T2>.TestGenericNested<byte, short>? @value,
			T1 @a,
			T2 @b
		)
		{
			Value = @value;
			A = @a;
			B = @b;
		}
	}

}
