//HintName: UnionCaseAttribute.g.cs
// <auto-generated>
// This code was generated by UnionStruct.
// </auto-generated>

#nullable enable

namespace UnionStruct;

[global::System.AttributeUsage(global::System.AttributeTargets.Method)]
public sealed class UnionCaseAttribute : global::System.Attribute;