namespace UnionStruct.Internals.Utils;

internal static class SourceBuilderUtils
{
	private const string _fileHeader =
		$"""
		 // <auto-generated>
		 // This code was generated by {GeneratorConstants.RootNamespace}.
		 // </auto-generated>
		 """;

	public static string Build(CodeWriter codeWriter)
	{
		return Build(codeWriter.ToString());
	}

	public static string Build(string sourceCode)
	{
		string template =
			$"""
			 {_fileHeader}

			 #nullable enable

			 {sourceCode}
			 """;

		return template.Replace("\r", string.Empty);
	}

	public static string ToEscapedLocal(string name)
	{
		name = name.RemovePrefix("@").RemovePrefix("_");
		return $"@{name.FirstCharToLowerCase()}";
	}

	private static string RemovePrefix(this string name, string prefix)
	{
		if (!name.StartsWith(prefix, StringComparison.Ordinal))
			return name;

		if (name.Length == prefix.Length)
			throw new InvalidOperationException($"Invalid identifier '{name}'.");

		return name.Substring(prefix.Length);
	}
}
