<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">

	<PropertyGroup Label="Build configuration">
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AnalysisMode>All</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
		<Features>strict</Features>
		<UseArtifactsOutput>true</UseArtifactsOutput>
	</PropertyGroup>

</Project>
